package app.terminal.com.serialport.inter;

/**
 * Created by liu.yao on 2016/5/24.
 */
public interface BroadcastIntface {
    String GETREADERID_BROADCASTRECEIVER = "GETREADERID_BROADCASTRECEIVER";
    String GETCARDDATA_BROADCASTRECEIVER = "GETCARDDATA_BROADCASTRECEIVER";
    String GETCONTROL_BROADCASTRECEIVER = "GETCONTROL_BROADCASTRECEIVER";
    String CONFLICT_BROADCASTRECEIVER = "CONFLICT_BROADCASTRECEIVER";
    String CHECKCTRLKEY_BROADCASTRECEIVER = "CHECKCTRLKEY_BROADCASTRECEIVER";
    String GETCURRENTCTRLKEY_BROADCASTRECEIVER = "GETCURRENTCTRLKEY_BROADCASTRECEIVER";

}
